"""initial_schema_10_tables

Revision ID: 3aa7020a9881
Revises: 
Create Date: 2026-05-11 14:10:10.702284
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa7020a9881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('approval_type', sa.Enum('SKILL', 'HIGH_RISK_STEP', name='approvaltype'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('memory_type', sa.Enum('EXECUTION_EXPERIENCE', 'WORKFLOW_PATTERN', 'DOMAIN_KNOWLEDGE', 'ERROR_SOLUTION', 'USER_PREFERENCE', 'PERSONAL_PROJECT', 'FILE_KNOWLEDGE', 'REMINDER', 'DAILY_CONTEXT', name='memorytype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_task_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_user_active', 'memories', ['user_id', 'is_active'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'STABLE', 'DISABLED', 'DEPRECATED', name='skillstatus'), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('source_task_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PLANNING', 'AWAITING_APPROVAL', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('edition', sa.Enum('ENTERPRISE', 'PERSONAL', name='edition'), nullable=True),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'PLAN_GENERATED', 'POLICY_CHECK', 'POLICY_APPROVED', 'POLICY_REJECTED', 'STEP_EXECUTING', 'STEP_COMPLETED', 'STEP_FAILED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_CANCELLED', 'MEMORY_WRITTEN', 'SKILL_EXTRACTED', 'SKILL_APPROVED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', name='auditeventtype'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_task_id', 'audit_events', ['task_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_messages_conv_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('skill_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_runs_skill_id', 'skill_runs', ['skill_id'], unique=False)
    op.create_table('task_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POLICY_CHECK', 'APPROVED', 'REJECTED', 'EXECUTING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('capability_token_hash', sa.String(length=128), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_steps_task_id', 'task_steps', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_steps_task_id', table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index('ix_skill_runs_skill_id', table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_index('ix_conv_messages_conv_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_audit_events_task_id', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('tasks')
    op.drop_table('skills')
    op.drop_index('ix_memories_user_active', table_name='memories')
    op.drop_table('memories')
    op.drop_table('edition_profiles')
    op.drop_table('conversations')
    op.drop_table('approvals')
    # ### end Alembic commands ###
